# Generated by Django 4.2.24 on 2025-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='头像')),
                ('detail_url', models.URLField(blank=True, verbose_name='详情页面')),
                ('original_image_url', models.URLField(blank=True, verbose_name='原始头像链接')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='评价总数')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='平均评分')),
                ('difficulty_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='难度评分')),
                ('would_take_again', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='再次选择率')),
                ('subjects', models.CharField(blank=True, help_text='用逗号分隔多个科目', max_length=500, verbose_name='教授科目')),
                ('department', models.CharField(default='计算机与软件工程', max_length=200, verbose_name='系别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ['-average_rating', '-total_reviews'],
            },
        ),
    ]
