# Generated by Django 4.2.24 on 2025-09-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='would_take_again',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='再次选择率'),
        ),
    ]
