# Generated by Django 4.2.24 on 2025-09-26 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, default='匿名', max_length=100, verbose_name='评价者姓名')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='总体评分')),
                ('difficulty_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度评分')),
                ('would_take_again', models.BooleanField(default=False, verbose_name='是否愿意再次选择')),
                ('course', models.CharField(choices=[('PSP', '问题解决与编程'), ('OOP', '面向对象编程'), ('AOOP', '高级面向对象编程'), ('SE', '软件工程'), ('SAaT', '软件分析与测试'), ('HCI', '人机交互'), ('DevOps', 'DevOps'), ('IPD', '创新产品开发'), ('OTHER', '其他')], default='OTHER', max_length=50, verbose_name='课程')),
                ('semester', models.CharField(choices=[('FALL_2024', '2024秋季学期'), ('SPRING_2024', '2024春季学期'), ('FALL_2023', '2023秋季学期'), ('SPRING_2023', '2023春季学期'), ('OTHER', '其他学期')], default='OTHER', max_length=50, verbose_name='学期')),
                ('title', models.CharField(max_length=200, verbose_name='评价标题')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔，如：认真负责,讲解清楚,作业适中', max_length=500, verbose_name='标签')),
                ('pros', models.TextField(blank=True, verbose_name='优点')),
                ('cons', models.TextField(blank=True, verbose_name='缺点')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='有用投票数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'verbose_name': '有用投票',
                'verbose_name_plural': '有用投票',
                'unique_together': {('review', 'ip_address')},
            },
        ),
    ]
